### ISSUE TITLE
React Native todo app get stuck on npm and crashes when built on Mac

### ISSUE THREAD

**Issue by kshehata** [mongodb-university/realm-template-apps#162] opened 2023-08-27 11:30 UTC
I'm trying to follow the tutorial here, but every time I run the sample app it crashes immediately.
https://www.mongodb.com/docs/atlas/app-services/tutorial/react-native/

Here's what I'm running:

``` bash
realm-cli pull --remote [name of my app in atlas] --template react-native.todo.flex
cd TutorialApp/frontend/react-native.todo.flex
npm install
```

This will get stuck on reifying realm. So I blow away node_modules and packages-lock.json and run yarn instead.

``` bash
rm -rf node_modules package-lock.json
yarn
npx pod-install
npx react-native run-ios
```

It takes a long time, but eventually tries to run the app. When it does, the app simply crashes with a BAD_ACCESS error. This is really weird because I'm able to build and run other React Native apps.

What gives? Am I doing something wrong here?

More details:
Mac OS X Ventura 13.4
XCode 14.3.1
2020 Intel MacBook Pro

**Comment by MongoCaleb** [comment] 2023-08-30 18:17
@kshehata thanks for reporting this! I am seeing the same thing on my M1, while other configurations are working just fine. We're investigating.

**Comment by kshehata** [comment] 2023-08-31 04:23
Ok, let me know if there's anything I can do on this end to help debug.

**Comment by kshehata** [comment] 2023-09-01 08:27
I started with the React Native starter app and then brought things over and now I have something that at least runs in the simulator. Not sure why this works and the repo here doesn't.

https://github.com/kshehata/TodoApp

**Comment by krollins-mdb** [comment] 2023-09-06 19:31
@kshehata, can you share the following info?
- Node.js version
- In the failing project, run `npm install -d verbose realm` and copy-paste the results here

This is potentially a problem with Node.js and Realm.js version compatibility. If so, I'd like to let the engineering team know or at least add warnings to the tutorial.

Realm.js had [a known issue](https://github.com/realm/realm-js/issues/5547) with Node.js v19, but that should have been addressed a long time ago. v11.5.2 had a fix for it.

**Comment by krollins-mdb** [comment] 2023-09-06 19:32
@MongoCaleb, you were on Node.js v20.something, right?

**Comment by kshehata** [comment] 2023-09-07 02:32
`node --version` tells me v20.3.0

I switched to yarn as npm would just stall on reifying. If I run npm with those options I get:

```
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "from" argument must be of type string. Received undefined
```

**Comment by kshehata** [comment] 2023-09-07 02:34
Not sure if this helps, here's what happens if I run yarn:

```
(base) user@machine react-native.todo.flex % yarn add -d verbose realm
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @realm/react@0.4.3" has incorrect peer dependency "realm@^11.0.0-rc || ^11.0.0".
warning "@realm/react > react-native@0.72.4" has incorrect peer dependency "react@18.2.0".
warning "@realm/react > react-native > @react-native/codegen@0.72.6" has unmet peer dependency "@babel/preset-env@^7.1.6".
warning "@realm/react > react-native > @react-native/codegen > jscodeshift@0.14.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
warning "react-native > react-native-codegen > jscodeshift@0.13.1" has unmet peer dependency "@babel/preset-env@^7.1.6".
warning " > @react-native-community/eslint-config@3.2.0" has unmet peer dependency "prettier@>=2".
warning "@react-native-community/eslint-config > eslint-plugin-prettier@4.2.1" has unmet peer dependency "prettier@>=2.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 4 new dependencies.
info Direct dependencies
└─ realm@12.1.0
info All dependencies
├─ bson@4.7.2
├─ node-machine-id@1.1.12
├─ prebuild-install@7.1.1
└─ realm@12.1.0
✨  Done in 8.60s.
```

**Comment by krollins-mdb** [comment] 2023-09-07 14:34
I can replicate when using Node.js v20.3.0. I'll make sure the engineering team is aware and see if we can come up with a workaround while they're looking into a fix.

**Comment by krollins-mdb** [comment] 2023-09-07 14:43
@kshehata, could you try using an older Node.js version (v18.16.0 works for me) to help determine whether the issue is compatibility with Node.js v20.3.0?

**Comment by krollins-mdb** [comment] 2023-09-13 19:56
@kshehata, seems like the problem was something in the project's `package-lock.json` file. If you delete that and then `npm install`, it should work.

I have [a PR up](https://github.com/mongodb-university/realm-template-apps/pull/166) to address this with the template app itself.

Thanks for filing this issue!

**Comment by krollins-mdb** [comment] 2023-10-17 15:04
I can install the template app locally now when using Node.js v20.3.0. Closing this issue. Let me know if you still experience problems.

**Closed by krollins-mdb** 2023-10-17 15:04 UTC
