### ISSUE TITLE
SwiftUI template app unable to maintain connection with flexible sync

### ISSUE THREAD

**Issue by atdyer** [mongodb-university/realm-template-apps#151] opened 2023-05-12 13:05 UTC
The SwiftUI template todo app is unable to maintain a connection with MongoDB. The app itself works just fine, but it is unable to sync. The steps I'm taking are:

1. Create a new app and download zip file from Atlas App Services
2. Ensure appId and appUrl are correct in atlasConfig.plist
3. Build and launch app on iPhone 14 Pro simulator
4. Create a user via app and log in to the app
5. Create todo items

I can see the created user in App Services, but no todos are ever synced. Opening the app on a different simulator confirms that there is no syncing happening. The following is output when the app launches and attempts to connect to flexible sync (I've removed some identifying info from these logs):

```
Sync: Realm sync client ([realm-core-13.10.1])
Sync: Connection[1]: Session[1]: Binding '[obfuscatedpath]/flx_sync_default.realm' to ''
Sync: Connection[1]: Session[1]: client_reset_config = false, Realm exists = true, client reset = false
Sync: Connected to endpoint 'x.xx.xxx.xx:xxx' (from 'xxx.xxx.x.xx:xxxxx')
Sync: Connection[1]: Closing the websocket with status='SystemError: invalid certificate chain', was_clean='false'
Sync: Connection[1]: Connection closed due to error
```

**Comment by MongoCaleb** [comment] 2023-08-30 19:50
Hi @atdyer  - Thanks for reporting this. We're not able to reproduce this in our test apps. Can you please be sure you have the most recent SDK installed, rebuild, and try again?

**Comment by dacharyc** [comment] 2023-12-05 21:37
Closing this issue as it has been a while with no reply. If you get back to this at some point and are still having problems, @atdyer , feel free to re-open or file a new issue.

**Closed by dacharyc** 2023-12-05 21:37 UTC
