### ISSUE TITLE
SwiftUI project doesn't work in offline mode when upgrading to latest package version. 

### ISSUE THREAD

**Issue by dvhull** [mongodb-university/realm-template-apps#183] opened 2024-01-23 22:31 UTC
https://github.com/mongodb-university/realm-template-apps/tree/20d5e3b39c30e777a2d2204cd122e72e7c0bf0d3/sync-todo/v2/client/swiftui

Upgrading to latest package version causes sync connection errors within the application.

**Comment by dacharyc** [comment] 2024-01-25 18:04
Hey @dvhull  - sorry you're having problems!

I'm not able to replicate this issue. Could you give me some more information to help me try to troubleshoot?

- What are the version numbers of Realm and RealmDatabase that are listed in your Package Dependencies?
- Can you confirm you have the correct App Services App ID in the `appId` field of `App/atlasConfig.plist`?
- Can you let me know what error you're seeing, and when?

**Comment by dvhull** [comment] 2024-01-28 22:54
Hey, thank you for the quick reply @dacharyc. Very sorry on the late reply. I will try to be more specific in what I am addressing as my initial issue was not specific enough. 

Realm version number: 10.46.0

Realm Database: 13.26.0

Xcode: 15.0.1

I have the correct App Services APP ID in the plist. The application works as expected with an internet connection. 

Steps to reproduce: 
1. Clone https://github.com/mongodb/template-app-swiftui-todo
2. Add App ID etc.... 
3. Install on physical device.
4. Log in and create an account. 
5. Add a item to the list. 
6. Turn on airplane mode.
7. Wait 5 minutes-ish and re-enter the app. 
8. The error that is shown is, "Failed to connect to sync: Host not found (authoritative)" 

To my understand @AutoOpen should make the realm offline first. So once the user is authenticated they shouldn't be locked out of the app? 

If you need more clarification I can upload a repo and you can take a look. Thank you.

**Comment by dacharyc** [comment] 2024-01-29 22:32
Hey @dvhull - thank you for the details to reproduce! I wasn't able to reproduce this on a simulator, but I was able to reproduce on a physical device. That may be a useful detail.

I would encourage you to open a support case to make engineering aware of this. You can find more information about how to open a support case in our documentation's [Get Help](https://www.mongodb.com/docs/realm/help/#professional-support) page. Feel free to link to this GitHub issue as a simple reproduction case. I will also raise this internally with the engineering team, but it always helps to prioritize work when we have a customer case to associate with it.

**Comment by dvhull** [comment] 2024-02-12 19:32
Hey @dacharyc, 

I have a MongoDB developer account were I pay $49 dollars a month. To open a support case what level do I need to be? I try to click "Create New Case" I am brought to a page that says, "Not Enabled for Support." I have emailed support-operations@mongodb.com but so far no response. 

Is there any work around to get offline mode to work with @autoOpen? I pass in my realm from the @autoOpen and access it with @Environment(\.realm) every time I need to write in my app. 

The app I have is a subscription based app fitness app where offline mode is paramount for my apps subscription retention. I tried to lower to package but I believe cause the local realm file change it is not possible. Any help or suggestions would be great. Thanks.

**Comment by dacharyc** [comment] 2024-02-20 14:26
Closing the loop here - engineering has identified the issue and has provided a workaround on this realm-swift GitHub issue: https://github.com/realm/realm-swift/issues/8469#issuecomment-1949536023

Based on your reply there, it looks like this has worked for you, @dvhull . I'll leave this issue open for now until we either adopt this workaround in the template app, or until the underlying issue is addressed.

Thanks for reporting this!

**Comment by dacharyc** [comment] 2024-05-03 11:41
Hey @dvhull - the [v10.50.0](https://github.com/realm/realm-swift/releases/tag/v10.50.0) `realm-swift` release appears to address the remaining offline issues with `@AutoOpen`, so you should be able to remove the workaround after you update to this version. I'm going to go ahead and close this issue as I believe this is now resolved. Do let us know if you have any other issues after updating to this version.

However, please note that [v10.49.3](https://github.com/realm/realm-swift/releases/tag/v10.49.3) changed the way to manage the SDK with Swift Package Manager. You can find details in the updated documentation - you'll need to remove the `Realm` library dependency, and you also need to build the framework dynamically if you want to use our provided Privacy Manifest. You can find details in this troubleshooting section, and in the updated Installation with Swift Package Manager procedure:

- https://www.mongodb.com/docs/atlas/device-sdks/sdk/swift/test-and-debug/#swift-package-target-cannot-be-built-dynamically
- https://www.mongodb.com/docs/atlas/device-sdks/sdk/swift/install/#installation

**Closed by dacharyc** 2024-05-03 11:41 UTC
